  #NGINX() {
#    CHECK_ROOT
#    PRINT "Installing NGINX"
#    yum install nginx -y &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Download ${COMPONENT} Content"
#    curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Clean OLD Content"
#    cd /usr/share/nginx/html
#    rm -rf * &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Extract ${COMPONENT} Content"
#    unzip /tmp/${COMPONENT}.zip &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Organize ${COMPONENT} Content"
#    mv ${COMPONENT}-main/* . && mv static/* . && rm -rf ${COMPONENT}-main README.md &>>${LOG} && mv localhost.conf /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#
#    PRINT "Update ${COMPONENT} Content"
#    sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#
#    PRINT "Start Nginx Service"
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
#    CHECK_STAT $?
#  }

- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import Common Role for code download
  ansible.builtin.include_role:
    name: common
    tasks_from: download