
#      APP_COMMON_SETUP
#
#      PRINT "Install NodeJS Dependencies"
#      mv ${COMPONENT}-main ${COMPONENT} && cd ${COMPONENT} && npm install &>>${LOG}
#      CHECK_STAT $?
#
#      SYSTEMD
#    }

- name: Setup the YUM Repos for NODEJs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed


- name: Import Common App Setup Configurations
  ansible.builtin.include_role:
    name: common
    tasks_from: download


- name: Install Nodejs Dependencies
  community.general.npm:
    path: "{{ APP_LOCATION }}"